language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pwgsc-intranet' ]; then cd .. && eval "mv $currentfolder generator-pwgsc-intranet" && cd generator-pwgsc-intranet; fi

